---
# Bestimmt welcher Musikplayer geladen werden soll:
# "pygame" für den lokalen Player
# "spotify" für den Musik-Server-Player welcher mit Spotify verbunden ist.  
player_type: pygame

#Namen der Datenen welche im "tracks" Ordner liegen.
pygame_playlists:

  angry:
  - "Simon Panrucker - Angry Dance.mp3"
  - "Bullet For My Valentine - Knives.mp3"
  disgusted:
  - "Helene Fischer - Atemlos durch die Nacht.mp3"
  - "Vincent Gross - Ich schenk Dir mein Herz.mp3"
  
  fearful:
  - "Charlie Clouser - Hello Zepp + Overture.mp3"
  - "DJ Haunted - Dark Ambient Music.mp3"
  - "Gold Rush Studio Orchestra - Jaws (Main Movie Theme).mp3"
  
  happy:
  - "Ketsa - Good Vibe.mp3"
  - "Ketsa - My happy place.mp3"
  - "mixkit-oh-lord-200.mp3"
  - "Jendrik - I Don't Feel Hate.mp3"
  - "Mark Ronson - Uptown Funk (feat. Bruno Mars).mp3"
  - "Pharrell Williams - Happy - From 'Despicable Me 2'.mp3"
  neutral:
  - "Bohoman - Elevator Music.mp3"
  - "Neeraj Make - Elevator Music.mp3"
  
  sad:
  - "A Great Big World, Christina Aguilera - Say Something.mp3"
  - "Coldplay - Fix You.mp3"
  - "Maggie Rogers - Past Life.mp3"
  - "Tate McRae - you broke me first.mp3"
  - "Valera - Everything.mp3"
  surprised:
  - "Kool & The Gang - Celebration.mp3"
  - "Los Del Rio - Macarena.mp3"

#Die Playlists, welche bei der jew. Emotion abgespielt werden sollen.
#Muessen in dem Format "<Playlistname> (by <Profilname>)" angegeben werden
#Müssen sich außerdem in der Bibliothek des verknüpften Spotify-Accounts befinden. (Geherzt oder selber erstellt)
spotify_playlists:

  angry: 'angry music  (by alexkokosko)'
  disgusted: 'DISGUSTED! (by shannonobrien6)'
  fearful: 'Fear The Walking Dead: The Ultimate Soundtrack (by 11181446986)'
  happy: 'Happy Hits! (by spotify)'
  neutral: 'Background Music (by oxob2090gqlwewrx3xxjmnbf3)'
  sad: 'Sad Songs 😢 for crying myself to sleep. (by sanik007)'
  surprised: 'You & Me (by spotify)'